'use strict';

// tests for update
// Generated by serverless-jest-plugin

import {APIGatewayProxyResult} from "aws-lambda";

import {handler} from "../../src/point/point.index";
import {handler as measurementHandler} from '../../src/measurement/measurement.index';
import eventGenerator from '../../src/testUtils/eventGenerator';
import * as jestPlugin from 'serverless-jest-plugin';
import {isApiGatewayResponse} from '../../src/testUtils/validators';

const wrapped = jestPlugin.lambdaWrapper.wrap(handler, { handler: 'update' });

describe('update', () => {
	beforeAll((done) => {
		done();
	});

	it('should return 200 and updated measurement', async () => {
		const measurementParams = eventGenerator.APIGatewayRequest(
			{
				body: {
					name: 'test',
				}
			}
		);
		const result = await measurementHandler.create(measurementParams);
		const measurement = JSON.parse(result.body);

		const points = eventGenerator.APIGatewayRequest(
			{
				body: [
					{
						x: 1,
						y: 1,
						z: 1,
						accuracy: 1,
					}
				],
				pathParametersObject: {
					measurementId: measurement.data.id,
				},
			}
		);
		const pointResponse = await handler.create(points);
		const point = JSON.parse(pointResponse.body).data[0];

		const params = eventGenerator.APIGatewayRequest(
			{
				pathParametersObject: {
					pointId: point.id,
				},
				body: {
					x: 2,
					y: 2,
					z: 2,
					accuracy: 2,
				}
			}
		);

		const response: APIGatewayProxyResult = await wrapped.run(params) as APIGatewayProxyResult;

		expect(response).toBeDefined();
		expect(response.statusCode).toBe(200);
		expect(isApiGatewayResponse(response)).toBe(true);

		const data = JSON.parse(response.body).data;
		expect(data).toEqual({
			id: point.id,
			x: 2,
			y: 2,
			z: 2,
			accuracy: 2,
			measurementId: measurement.data.id,
			updatedAt: expect.any(String),
		});
	});

	it('should return 400 if we dont pass an id', async () => {
		const params = eventGenerator.APIGatewayRequest(
			{
				pathParametersObject: {
					pointId: ''
				},
			}
		);

		const response: APIGatewayProxyResult = await wrapped.run(params) as APIGatewayProxyResult;
		expect(response).toBeDefined();
		expect(response.statusCode).toBe(400);
		expect(isApiGatewayResponse(response)).toBe(true);
	});

	it('should return 422 if the point is not valid', async () => {
		const measurementParams = eventGenerator.APIGatewayRequest(
			{
				body: {
					name: 'test',
				}
			}
		);
		const result = await measurementHandler.create(measurementParams);
		const measurement = JSON.parse(result.body);

		const points = eventGenerator.APIGatewayRequest(
			{
				body: [
					{
						x: 1,
						y: 1,
						z: 1,
						accuracy: 1,
					}
				],
				pathParametersObject: {
					measurementId: measurement.data.id,
				},
			}
		);
		const pointResponse = await handler.create(points);
		const point = JSON.parse(pointResponse.body).data[0];

		const params = eventGenerator.APIGatewayRequest(
			{
				pathParametersObject: {
					pointId: point.id,
				},
				body: {
					x: '',
					y: '',
					z: '',
					accuracy: '',
				}
			}
		);

		const response: APIGatewayProxyResult = await wrapped.run(params) as APIGatewayProxyResult;
		expect(response).toBeDefined();
		expect(response.statusCode).toBe(422);
		expect(isApiGatewayResponse(response)).toBe(true);
	});
});
