'use strict';

// tests for findAll
// Generated by serverless-jest-plugin

import {APIGatewayProxyResult} from "aws-lambda";
import {handler} from '../../src/measurement/measurement.index';
import * as jestPlugin from 'serverless-jest-plugin';
import {isApiGatewayResponse} from '../../src/testUtils/validators';

const wrapped = jestPlugin.lambdaWrapper.wrap(handler, { handler: 'findAll' });

describe('findAll', () => {
	beforeAll((done) => {
		done();
	});

	it('should return a 200 whit the list of measurements', async () => {
		const response: APIGatewayProxyResult = await wrapped.run({}) as APIGatewayProxyResult;
		expect(response).toBeDefined();
		expect(response.statusCode).toBe(200);
		expect(isApiGatewayResponse(response)).toBe(true);

		const body = JSON.parse(response.body);
		expect(body.data[0]).toEqual({
			id: expect.any(String),
			name: expect.any(String),
			createdAt: expect.any(String),
			updatedAt: expect.any(String),
		});
	});
});
