'use strict';

// tests for update
// Generated by serverless-jest-plugin

import {APIGatewayEvent, APIGatewayProxyResult} from "aws-lambda";

import {handler} from '../../src/measurement/measurement.index';
import eventGenerator from '../../src/testUtils/eventGenerator';
import * as jestPlugin from 'serverless-jest-plugin';
import {isApiGatewayResponse} from '../../src/testUtils/validators';

const wrapped = jestPlugin.lambdaWrapper.wrap(handler, { handler: 'update' });

describe('update', () => {
	beforeAll((done) => {
		done();
	});

	it('should return 200 and updated measurement', async () => {
		const body: APIGatewayEvent = eventGenerator.APIGatewayRequest(
			{
				body: {
					name: 'test',
				}
			}
		);
		const result = await handler.create(body);
		const ID = JSON.parse(result.body).data.id;

		const params = eventGenerator.APIGatewayRequest(
			{
				pathParametersObject: {
					id: ID
				},
				body: {
					name: 'test2',
				}
			}
		);

		const response: APIGatewayProxyResult = await wrapped.run(params) as APIGatewayProxyResult;
		expect(response).toBeDefined();
		expect(response.statusCode).toBe(200);
		expect(isApiGatewayResponse(response)).toBe(true);

		const data = JSON.parse(response.body).data;
		expect(data.name).toBe('test2');
	});

	it('should return 400 if we dont pass an id', async () => {
		const params = eventGenerator.APIGatewayRequest(
			{
				pathParametersObject: {
					id: ''
				},
				body: {
					name: 'test2',
				}
			}
		);

		const response: APIGatewayProxyResult = await wrapped.run(params) as APIGatewayProxyResult;
		expect(response).toBeDefined();
		expect(response.statusCode).toBe(400);
		expect(isApiGatewayResponse(response)).toBe(true);
	});

	it('should return 422 if the measurement is not valid', async () => {
		const body = eventGenerator.APIGatewayRequest(
			{
				body: {
					name: 'test',
				}
			}
		);
		const result = await handler.create(body);
		const ID = JSON.parse(result.body).data.id;

		const params = eventGenerator.APIGatewayRequest(
			{
				pathParametersObject: {
					id: ID
				},
				body: {
					name: '',
				}
			}
		);

		const response: APIGatewayProxyResult = await wrapped.run(params) as APIGatewayProxyResult;
		expect(response).toBeDefined();
		expect(response.statusCode).toBe(422);
		expect(isApiGatewayResponse(response)).toBe(true);
	});
});
